### ISSUE TITLE
DateTime marshaller truncates fractional seconds

### ISSUE THREAD

**Issue by kdeldycke** [flask-restful/flask-restful#368]
The `flask_restful.inputs.iso8601()` utility method is truncating fractional seconds, which makes the marshalling of date-times loosing fractional precision.

I don't see a rationale for removing milli/microseconds as this level of precision is supported by ISO 8601 and Python.

**Comment by ianozsvald** [comment]
+1 I've just run into this bug, I'm using a fixture created from real data. 

Also the addition of tzinfo=tzutc() by default on the same line, rather than only if it was there in the original, causes a bug for me. Arguably the utc case means I should be forcing a utc tz earlier in my code so your addition of the tz is probably the sane choice (so I note it, but I'm not claiming it to be a bug).

**Comment by joshfriend** [comment]
Gaahh, its bad in both `inputs` [_and_ `fields`](https://github.com/flask-restful/flask-restful/blob/bf983cf706c9f55e5789f621f2ce9182f01d9636/flask_restful/inputs.py#L271-L273)
