### ISSUE TITLE
Unskip tests added in #245

### ISSUE THREAD

**Issue by joshfriend** [flask-restful/flask-restful#392]
Remove the skip on the test that failed in #245 because [werkzeug 0.10](https://github.com/mitsuhiko/werkzeug/releases/tag/0.10) was not released yet.

**Comment by joshfriend** [comment]
the `test_media_types_q` case is also failing with the werkzeug update.

**Comment by joshfriend** [comment]
@jrandall  do you have any ideas why additional tests are failing after the werkzeug update? I have not had time to look into it yet and thought I would ask since you are already familiar with some of this.

**Comment by jrandall** [comment]
I haven't looked yet but I'll check it out now.

**Comment by jrandall** [comment]
Ok, yes I see the issue is that the `test_media_types_q` test case (which predates these changes) tests an invalid `Accept` header: `'Accept': 'application/json; q=1; application/xml; q=.5'` 

This is not a valid HTTP Accept header according to (rfc2616)[http://www.ietf.org/rfc/rfc2616.txt] because the two `media-range [ accept-params ]` entries need to be delimited by commas, not semicolons.

The ABNF for Accept (rfc2616 section 14.1) is:
```ABNF
Accept         = "Accept" ":"
                        #( media-range [ accept-params ] )

       media-range    = ( "*/*"
                        | ( type "/" "*" )
                        | ( type "/" subtype )
                        ) *( ";" parameter )
       accept-params  = ";" "q" "=" qvalue *( accept-extension )
       accept-extension = ";" token [ "=" ( token | quoted-string ) ]
```

Note that the `#()` syntax in ABNF means to separate the list by commas with optional whitespace. 

Applying the following patch should fix it.
```patch
--- a/tests/test_api.py
+++ b/tests/test_api.py
@@ -519,7 +519,7 @@ class APITestCase(unittest.TestCase):
         api = flask_restful.Api(app)

         with app.test_request_context("/foo", headers={
-            'Accept': 'application/json; q=1; application/xml; q=.5'
+            'Accept': 'application/json; q=1, application/xml; q=.5'
         }):
             self.assertEquals(api.mediatypes(),
                               ['application/json', 'application/xml'])
```

**Comment by joshfriend** [comment]
Thanks for your help on this!
