### ISSUE TITLE
Release a 0.3.2

### ISSUE THREAD

**Issue by noirbizarre** [flask-restful/flask-restful#400]
Hi!

There has been some fixes since the 0.3.1. 
How about a 0.3.2 release ?

**Comment by joshfriend** [comment]
I had some issues mapped out to be included in a 0.3.2 release [here](https://github.com/flask-restful/flask-restful/milestones/0.3.2), but maybe that's too many to handle all at once. The only one I'm set on including is #392 because it's making tests fail currently.

I think there's been enough significant fixes that I can make a new release a high priority.

**Comment by joshfriend** [comment]
Done! see #403

**Comment by noirbizarre** [comment]
Thanks !!!

By the way I will propably do some pull-requests on the roadmap features.
