### ISSUE TITLE
How I can parse multiple arguments in GET query using reqparse?

### ISSUE THREAD

**Issue by defuz** [flask-restful/flask-restful#423]
I want to parse URLs like this:

    /api/endpoint?field=1&field=2

But if I try to do this with `RequestParser` I get only one value of `field` argument. Is there any way to get a list of values for multiple arguments? If not, what do you think of this approach:

    parser = reqparse.RequestParser()
    parser.add_argument('source_apps', type=str, multiple=True)

The parameter `multiple=True` means that the method `parser.parse_args` will return *a list* of all the specified values.

**Comment by skimbrel** [comment]
Just like in argparse, pass `action='append'` to the argument to get it to return all found values in a list.

**Comment by venix** [comment]
@skimbrel I am using action='append' for an argument i.e let's say field. But when only one value is passed i.e /api/endpoint/field=1 this is returned as a single value instead of a list with that value appended. For example for field=1 it then parsed_args.get('field') will return 1 instead of [1]. This causes problems when you might expect 1 or more values to be passed and you want to loop through the list of input values. Is there any way to resolve this issue without checking for the type in the request view ?

Am I missing something? 

Cheers, 
Michael
