### ISSUE TITLE
[Question] Why marshal returns a OrderedDict instead of a normal dict?

### ISSUE THREAD

**Issue by halfcrazy** [flask-restful/flask-restful#430]

**Comment by sebleblanc** [comment]
I guess it's so that when `jsonify` or whatever you are using will iterate over your fields, it will process the fields in the same order they were rendered.

It makes the output of your API more predictable, not that you should rely on the order of fields. I just find that for a User model, for instance, it's cleaner to have the id as the first field of your response, then the username, then the full name, then the profile, etc.

**Comment by skimbrel** [comment]
That was indeed the intent. It's nice to have fields with a consistent ordering for debugging and interacting with APIs on the command line.

**Comment by joshfriend** [comment]
> An object is an **unordered** set of name/value pairs.

source: [json.org](http://json.org)

Keep in mind that your field declarations also must be an `OrderedDict` and not a standard python `dict` or the order will not be preserved (see #377).

I think technically, the ordering is already predictable, but the order would be based on the hash of the keys.

Also, I second what @sebleblanc said, it would be a really bad idea to rely on the key ordering for anything but debugging.
