### ISSUE TITLE
Post is giving Problem 

### ISSUE THREAD

**Issue by SubhabrataBanerji** [flask-restful/flask-restful#447]
Dear Moderator,

I was trying to learn Flask restful from http://flask-restful.readthedocs.org/en/latest/quickstart.html. 
I could run the examples, but there are two issues,
a) As I was running the full example, I could get the data, could delete the data, but as I was trying to post the data it is posting but returning null, instead of the posting string. I am not quoting the server side script which you know already, 
I am citing the post request I am trying to make. Please see if I am making any error. 
var1=requests.post('http://127.0.0.1:5000/todos/todo2/post', data={'data': 'Change my brakepads'})

b) There is one minor issue:
as I am giving http://127.0.0.1:5000/ after running the first example it is showing 404 Error, but if I am
giving http://127.0.0.1:5000/todos after running the full example, it is working. 

If you may kindly see.

Regards,
Subhabrata Banerji

**Comment by joshfriend** [comment]
Looks like there are some errors with the way you are trying to interact with the quickstart example:

* Using `POST` instead of `PUT` for the HTTP method
* Including the HTTP method name in the URL
* Submitting malformed JSON payload. The request argument is named `task`, you supplied `data`, which is ignored by the parser and returns `null`.

Here's your example code, with the above errors fixed:

```python
var1=requests.put('http://127.0.0.1:5000/todos/todo2', data={'task': 'Change my brakepads'})
```

I'll fix the error you found (b) shortly...

**Comment by SubhabrataBanerji** [comment]
Dear Sir,

Thank you for your kind reply. Of late, I could also do in similar way.

Regards,
Subhabrata.
