### ISSUE TITLE
0.3.4 breaks Flask-Limiter tests

### ISSUE THREAD

**Issue by alisaifee** [flask-restful/flask-restful#489]
With the latest release this [test](https://github.com/alisaifee/flask-limiter/blob/master/tests/test_flask_ext.py#L782) starts failing as the exception detected [here](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L282) is `exceptions.AssertionError`

[failing test](https://travis-ci.org/alisaifee/flask-limiter/jobs/74047937#L231)

**Comment by alisaifee** [comment]
Strangely the tests don't fail on python 3.x

**Comment by joshfriend** [comment]
Looks like this is the same issue as #486:

```python
TypeError: 2 per 1 second is not JSON serializable
```

I opened alisaifee/flask-limiter#33 a second ago which fixes the issue (at least for flask-limiter).

It could also be patched in a similar way in Flask-RESTful, but I'm not sure I want to do that:

- The field name of `description` implies that it should be a string. Assigning some other object to that field doesn't seem like obvious behavior.
- In `werkzeug`, `HTTPException.description` is always a string and it seems wise to continue that pattern. Otherwise, it could be difficult in the future to maintain if any arbitrary data is allowed for `description`.

Open to suggestion/discussion if you have other thoughts.
