### ISSUE TITLE
restful url string or not str

### ISSUE THREAD

**Issue by wednesdaysunny** [flask-restful/flask-restful#537]
when I use url ad 
api.add_resource(Foo, '/Foo', '/Foo/<str:id>')
It is not right  and give me 'LookupError: the converter 'str' does not exist' tip
but when I use api.add_resource(Foo, '/Foo', '/Foo/<string:id>')
It is right and I can send a string paraml.
I have question , why there use string and not use str?
I think it is wrong.

**Comment by joshfriend** [comment]
This has nothing to do with Flask-RESTful. The routing configuration is [handled by the Werkzeug framework](http://werkzeug.pocoo.org/docs/0.11/routing/#werkzeug.routing.Rule) (which is what powers Flask and by association, Flask-RESTful).

I don't know this for sure, but my guess would be the converter is called "string" because `str` means two completely different things in python2 (non-unicode string) and python3 (a unicode string). The name was probably chosen to avoid ambiguity between these two.

**Comment by godmar** [comment]
Side note: the [current docs](https://flask-restful.readthedocs.io/en/latest/intermediate-usage.html#project-structure) contain this example, but do not make clear that it's Python 2 only.  Python 2 will [supposedly be retired 2020](https://pythonclock.org/)
