### ISSUE TITLE
Regression with 0.3.4 and Flask-Principal

### ISSUE THREAD

**Issue by bodgit** [flask-restful/flask-restful#543]
Please see mattupstate/flask-principal#42 for the issue I originally raised thinking it was against Flask-Principal. After a helpful comment it turns out everything works as expected if I downgrade Flask-RESTful to 0.3.3 but with 0.3.4 it breaks completely on Python 2.7.x and with Python 3.5.x I get an HTML error response instead of the expected JSON.

**Comment by kevgliss** [comment]
+1 on this, it is preventing me from upgrading flask-restful

**Comment by justanr** [comment]
Relevant code:

* [Werkzeug#Aborter.\_\_call\_\_](https://github.com/mitsuhiko/werkzeug/blob/5a2bf35441006d832ab1ed5a31963cbc366c99ac/werkzeug/exceptions.py#L654)
* [Werkzeug#HTTPException.\_\_init\_\_](https://github.com/mitsuhiko/werkzeug/blob/5a2bf35441006d832ab1ed5a31963cbc366c99ac/werkzeug/exceptions.py#L86)
* [Flask-Principal#IdentityContext.\_\_enter\_\_](https://github.com/mattupstate/flask-principal/blob/0b5cd06b464ae8b60939857784bda86c03dda1eb/flask_principal.py#L207)
* [Flask-Principal#PermissionError](https://github.com/mattupstate/flask-principal/blob/0b5cd06b464ae8b60939857784bda86c03dda1eb/flask_principal.py#L121) ***Note: This is a RUNTIME Error*** why, I could not tell you.
* [Change introduced in Restful#Api.handle_error 0.3.4](https://github.com/flask-restful/flask-restful/blob/63cadac8043e2070a22b5ab34a2656b804ef620f/flask_restful/__init__.py#L283)
* [Flask#Flask.handle_user_exception](https://github.com/mitsuhiko/flask/blob/c9b29f4072b66be4c751af060d64ea749c6991c1/flask/app.py#L1498)

My best guess is that because the raw PermissionError is being passed to abort AND aborter 

There's also this line in the traceback:

```
  File ".../venv/lib/python2.7/site-packages/flask_restplus/api.py", line 379, in handle_error
    return super(Api, self).handle_error(e)
```

That could also be the source of your trouble. Simply put, there's lots of moving parts in this and it's most likely an unknown/unexpected interaction between them. Specifically of interest could be how Flask-Restful and Flask handle catching and propagating errors:

In Flask-Restful:

```python
        if not isinstance(e, HTTPException) and current_app.propagate_exceptions:
            exc_type, exc_value, tb = sys.exc_info()
            if exc_value is e:
                raise
            else:
                raise e
```

in Flask, the particular block causing the assertion error

```python
        exc_type, exc_value, tb = sys.exc_info()
        assert exc_value is e
```

You could conveniently bypass this by running with `python -O` which disables `assert` statements but I'd honestly recommend against that as its a hack at best.

However, all of this can be avoided by registering an error handler for PermissionDenied (my preferred fix, but maybe not yours). I agree that this shouldn't happen but there's simply too many moving pieces for me to properly pin down the correct problem child and how to fix it.

If you're interested in fixing this, I'd recommend start by submitting PRs to Flask and Flask-Principal with these fixes:

* Flask: Change in line assert in handle_user_exception to an `if not exc_value is e: raise SomeException` so there's proper error reporting that something bad happened.
* Flask-Principal: Change PermissionError to extend from Exception rather than RuntimeError (as that's an improper exception type)

Or at the least, change these in local copies and see what happens from there.
