### ISSUE TITLE
Add catch_all_405s or ability to define custom error handler for 405 MethodNotAllowed Error

### ISSUE THREAD

**Issue by jakubczaplicki** [flask-restful/flask-restful#579]
Errors _404_ and _405_ are treated in a special way by Flask-Restful (see [_should_use_fr_error_handler()](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L217)). 

In case of _404 NotFound_, we can set the `catch_all_404s=False` flag, so that Flask's error handle will deal with the _404 NotFound_ exception.

There is no equivalent feature for _405 MethodNotAllowed_. And so every time a request hits _405_, the response will be `{'message': 'The method is not allowed for the requested URL.'}`. And that is even after registering custom error handler to Flask object:  `app.register_error_handler(Exception, my_custom_error_handler)`

It would be really useful to be able to set **catch_all_405s=False**, or ideally be able to define our own error handler for _405_ error.

Currently the only way to specify custom 405 error is by defining a non-dynamic dictionary:
e.g.

```
    'MethodNotAllowed': {
        'type': 'MethodNotAllowed',
        'description': 'The method is not allowed for the requested URL.',
        'url': None,
        'data': None,
        'status': 405
    }
```

This however won't allow us to update the dict elements such as 'url' in the given example.

**Comment by ashwinkumar01** [comment]
You can set a custom 405 message by redefining [Werkzeug's HTTP exceptions](http://werkzeug.pocoo.org/docs/0.11/exceptions/). Flask is based on Werkzeug's exceptions. An example of overriding 405 is below:
` errors = {  
     'MethodNotAllowed': {
            'result': 'False',
            'status': 405,
            'message': ['This method is not allowed for the requested resource']
    }
}
api = flask_restful.Api(errors=errors)
`

So if you raise a 405 or or use abort, this message that you define will be presented rather than the default response. This is also documented in [flask_restful's docs](http://flask-restful-cn.readthedocs.io/en/0.3.4/extending.html#define-custom-error-messages). However the doc states that only the 'status' key matters, but the error name also matters, which is why I made a pull request to update this in #597

**Comment by randyesq** [comment]
Is there any way to overwrite the Content-Type header using the method mentioned by @ashwinkumar01 ? I'd like my error responses to reflect the format of problem details in RFC7807, which uses 'application/problem+json' instead of 'application/json'.

**Comment by alrhos** [comment]
@jakubczaplicki - thanks this works really well!

**Comment by muteebakram** [comment]
Thank you this help :)

**Comment by onlinejudge95** [comment]
@jakubczaplicki why is this issue marked as completed?
