### ISSUE TITLE
faster marshal

### ISSUE THREAD

**Issue by vinczente** [flask-restful/flask-restful#618]
Hi,
Is there a way to make marshal go faster?
Thanks for your help.

**Comment by joshfriend** [comment]
There are so many things that could influence performance of marshaling. Since you haven't provided any context to your speed issue (or if there actually is one), the only suggestion I can offer at this point is to get a faster computer to run your application.

Does your application perform slowly all the time, or just on specific `Resource`s? Are you just asking how to improve performance in general?

If you use Python 2, you could try using [PyPy](http://pypy.org) instead of CPython.

**Comment by vinczente** [comment]
@joshfriend Can't understand why marshal is using OrderedDict instead of dict


https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L642

Can you help understand why it is important to keep the order ?

**Comment by songxiaowei112** [comment]
I think it should be for the sake of abnormal, can have order to exception error value is returned

________________________________
发件人: Vincent c <notifications@github.com>
发送时间: 2017年1月30日 13:18
收件人: flask-restful/flask-restful
抄送: Shane; Manual
主题: Re: [flask-restful/flask-restful] faster marshal (#618)


@joshfriend<https://github.com/joshfriend> Can't understand why marshal is using OrderedDict instead of dict

https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L642

Can you help understand why it is important to keep the order ?

―
