### ISSUE TITLE
Why access to a few protected members?

### ISSUE THREAD

**Issue by bdh1011** [flask-restful/flask-restful#632]
I found there are weird access on __init__ file.
Since _* member is protected, It should not be access.
Why below two line are accessing to protected member?

https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L17
https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L281

**Comment by justanr** [comment]
The `current_app._get_current_object()` is needed because that's the *actual* object that's being proxied to and does not require the application context. Whereas just passing `current_app` would be the proxy and might not be the application you were intending on passing.

As for `_endpoint_from_view`, it's patching how blueprints are setup and uses that function to reverse engineer the endpoint name if one is not explicitly given.

As for general `_thing` access, I look at it as a "This is an implementation detail, but you can use it if you know what you're doing". 

There's no actual concept of "protected" or "private" in Python (`_thing` is a community convention, and `__thing` gets name mangling but it's more about ensuring a name isn't overwritten than actual protections), and in languages with those concepts protected and private are just flip covers on dangerous switches. They're not there to *stop* you from doing something, they're there to make sure you actually want to do that.
