### ISSUE TITLE
Can´t retrieve accents when seleting from database - possible encoding error

### ISSUE THREAD

**Issue by diegovini** [flask-restful/flask-restful#657]
Hi guys, we are using Flask_Restful to create a Rest api here and we´re facing a small problem.

When retrieving from the db(Oracle 12), the accents of the words are being ignored. 
Example:

>
á becomes a
ç becomes ?
é becomes e   
and so on...
>

**Some additional info:**
We´re using # -*- coding: utf-8 -*- on the top of our coding files 
We have  tried to use 'os.environ["NLS_LANG"] = 'BRAZILIAN PORTUGUESE_BRAZIL.AL32UTF8', ', but it only changed the characters to other symbols...

We are new to Python(2,7) and we could not figured it out what is the problem behind this.

**Comment by joshfriend** [comment]
I don't think I have a concrete answer for you but here are some thoughts:

1. This problem is most likely not caused by flask or flask-restful. I would suspect a configuration issue with the database itself or with the parameters you use to connect to it. If you open a SQL prompt on the database itself without any python layers on top of it, do the diacritics appear correctly?
2. Perhaps somewhere in your code you are accidentally calling `encode()` on some data where you shouldnt? For example: `unicodedata.normalize('NFD', 'áçé').encode('ascii', 'ignore')` returns `b'ace'`
3. You would be doing yourself a huge favor if you use python3 instead of python2.

**Comment by diegovini** [comment]
I see, we're also using flask sqlalchemy. Maybe I am missing some parameters in the connection string?

Since you think it is not a flask nor flaskrestful problem, where should ee look for help if we cant resolve this issue?


1) We called our Dba and ge assured us that there was no configuration problem in the db. 
A query on the db, without any python layers, will retrieve the letters normally.

2)This was actually something I've tried before, but they are no longer in our code.

3) I believe some guys here decided for 2.7 because they thought it would be more stable than 3...
