### ISSUE TITLE
In README.md, here link in User Guide section does not work

### ISSUE THREAD

**Issue by pleycpl** [flask-restful/flask-restful#663]
http://flask-restful.readthedocs.io/en/latest/   => Sorry This page does not exist yet.

**Comment by joshfriend** [comment]
Sorry, the RTD project was [temporarily deleted due to a bug](https://github.com/flask-restful/flask-restful/issues/660#issuecomment-283128858) and I have not had time to resurrect the `/latest` docs. You can still view docs for the latest released version though: http://flask-restful.readthedocs.io/en/0.3.5/

**Comment by cdnsteve** [comment]
Created a PR which links to the root URI which seems to forward to the current latest docs
https://github.com/flask-restful/flask-restful/pull/668

**Comment by zcattacz** [comment]
I created a clone to download the epub version. https://readthedocs.org/projects/flask-restful-doc/builds/

**Comment by joshfriend** [comment]
@zcattacz If you can, please just send a PR to this repo that adds epub build support. Don't create documentation forks, it just confuses people. Thanks.
