### ISSUE TITLE
flask.abort in Flask-RESTful==0.3.7 is not work but in 0.3.6 is not work

### ISSUE THREAD

**Issue by wangxue666666** [flask-restful/flask-restful#825]
For example：
   `abort(jsonify(dict(code=code, msg=get_code_msg(code))))` is not work in 0.3.7,
`abort(404)` is work. if i modify my version to 0.3.6 is ok. Why this problem and what should I do?

**Comment by billyrrr** [comment]
Hi, I have added a test case.  Please let me know if the test case repeats your error. (since the test case fails for 0.3.6 also)

**Comment by billyrrr** [comment]
I have read over your comment in #826 . I see that the problem is that data is not returned when using flask.abort. This is similar to the issue #791 , which exists in version 0.3.7 and not in version 0.3.6. A fix (#817 ) was submitted by me a few months ago that should fix this problem. Does the test cases pass for the current master branch? If so, the issue may be solved once the new version is released. 

I also added a few test cases in pull request #827 , let me know what you think.

**Comment by wangxue666666** [comment]
Thank you very much. After modifying the code according to #791, the response is indeed normal
