### ISSUE TITLE
 DeprecationWarning

### ISSUE THREAD

**Issue by gkshindia** [flask-restful/flask-restful#832]
![DeprecationWarning](https://user-images.githubusercontent.com/25399360/66912031-66c7a580-f02f-11e9-9015-d151b009fcfa.png)

When I ran pytest, received the above warning.
**Fix** :
I replaced `from collections import Mapping` to `from collections.abc import Mapping` 
and ran the pytest again, the warning was gone.

Please note..
Thank you

**Comment by joshfriend** [comment]
Thanks for the tip!

PRs always welcome 😄

**Comment by laserpedro** [comment]
Hello guys, same issue for me: running pytest (py version = 3.7.7):

![image](https://user-images.githubusercontent.com/34578039/69715915-5e23be00-1109-11ea-88d6-cd1b411195f8.png)

**Comment by junwei-wang** [comment]
reverse the order 

tests/test_test.py::test_not_found[/random/path/1]
flask_restful/__init__.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html
