### ISSUE TITLE
How to handle POST request with `Content-Type: application/jwt`?

### ISSUE THREAD

**Issue by bertdida** [flask-restful/flask-restful#837]
How can I access the value using `reqparse`, if the request's header has  `Content-Type: application/jwt`?

**Comment by joshfriend** [comment]
you cannot do this with `reqparse` because flask itself doesnt provide a handler for this: 

https://flask-restful.readthedocs.io/en/latest/api.html#reqparse.Argument
https://github.com/flask-restful/flask-restful/blob/48ca816c9d116fd975182691c7b0d1bbb6c3e332/flask_restful/reqparse.py#L26-L34

You will have to decode that response body yourself
