### ISSUE TITLE
Flask App Hitting EndPoint Automatically after sometime

### ISSUE THREAD

**Issue by NT-19** [flask-restful/flask-restful#941]
Dear Friends,

I am struggling to solve a problem with Flask App end points. I researched online but couldn't find the the solution.

I have created an ETL (Extract/Transform/Load) process to extract millions of records from database. And the entire frame work is written in Python. Various ETL jobs has been exposed from the Flask API Endpoints using GET method.
The jobs are time consuming and can run for hours. 

**Problem:** As the jobs are exposed through Flask Endpoints and run for hours. Flask is hitting the API automatically after 45 mins or so. I don't want this to happen as the processing from first call didn't finish and 2nd call occurred. I noticed that the retries happen max 3 times. This is causing the contention and process overriding with each other . 

What is the solution to handle this issue that automatic retries didn't occur ?

Thank You

**Comment by joshfriend** [comment]
Please ask general questions about how to use Flask and Flask-RESTful on sites like Stack Overflow. Unless you have reason to believe that your issues are caused by a problem with Flask-RESTful and can explain how to replicate the issue, that will be your best option. You've not provided any information whatsoever on how to duplicate your problem here.
